In [1]:
import os
import pandas as pd

from gensim.corpora import WikiCorpus
from gensim.models import Word2Vec
from gensim.models.word2vec import LineSentence
import pandas as pd
import multiprocessing
import numpy as np
import pickle



In [50]:
#以下对app_id,site_id,site_domain进行w2v,完全可以写个函数进行封装，这里就算了


#以下对app_id进行w2v
import pickle
temp = pickle.load(open('app_id_history.pkl', 'rb'))
print(type(temp))

<class 'dict'>


In [51]:
L=6
sentence = []
for user,user_app_id_history in temp.items():
    sentence.append(user_app_id_history)
#print(sentence[:6])

[['a37bf1e4', 'a37bf1e4', '08a53ae7', '27550a3c', 'a37bf1e4', 'a37bf1e4', 'dfdd226c', 'dfdd226c', 'a37bf1e4', 'a37bf1e4', 'dfdd226c', 'a37bf1e4', '08a53ae7', '08a53ae7', 'a37bf1e4', '08a53ae7', '08a53ae7', 'c73fb408', 'c73fb408', 'c73fb408'], ['03528b27', '54c5d545'], ['c73fb408', 'c73fb408', 'c73fb408', '27550a3c', '27550a3c', '27550a3c'], ['03528b27', '03528b27', '03528b27', '54c5d545'], ['03528b27', '03528b27', 'e2a1ca37'], ['aaf0fa87', '442cfede', '442cfede', '442cfede']]


In [52]:
model = Word2Vec(sentence, size=L, window=2, min_count=1, workers=multiprocessing.cpu_count())

In [53]:
model['a37bf1e4']

c:\users\lx\appdata\local\programs\python\python37\lib\site-packages\ipykernel_launcher.py:1: DeprecationWarning: Call to deprecated `__getitem__` (Method will be removed in 4.0.0, use self.wv.__getitem__() instead).
  """Entry point for launching an IPython kernel.


array([ 1.1890088,  3.2032664,  3.8581412, -2.448969 , -1.2316612,
        0.5556142], dtype=float32)

In [54]:
app_id=pickle.load(open('app_id.pkl', 'rb'))

In [55]:
print(app_id)

['ecad2386', 'c3f39675', '3c4b944d', 'febd1138', '98fed791', 'e2fcccd2', '9c13b419', 'de97da65', '255a58c8', '3e2bf98d', '95827a92', '2d869bee', '3692fd30', '1dc72b4d', '03528b27', 'd292c32f', '08a53ae7', '51cedd4e', '27550a3c', 'e2a1ca37', 'f888bf4c', '5bea6a27', '0a365d8b', '92f5800b', '5325bfcf', '53de0284', '8f547596', '54c5d545', '1c4c71ef', 'da90aa44', 'e8937587', 'e109e9bd', '0acbeaa3', '39947756', '925db399', '7358e05e', '4e02fbd3', '7c7508aa', '120a00a5', 'cc1c2bd2', '2a34457c', 'a37bf1e4', '928e816b', '50b7d906', '6f1cef18', 'c73fb408', '643e0f88', 'ce183bbd', '72707178', '66f5e02e', 'd42361b6', '680e6a92', '8dbc921a', '89bdfe24', 'cb06b587', '89e8c66c', '3ca8346f', '1fccd444', '718e4622', 'dfdd226c', 'eb98984c', '6fc85e22', '28117800', '4fdcf4e6', '4201f5fd', '431a0d44', 'ccf7ce7e', 'a065fb4f', '0639409a', '93def835', '06cfa6da', '925c2ac6', '0d50fd9b', 'a0a45985', 'd44c074c', '48f4bdf9', 'c0a736f4', '65f37f55', '13684a79', '2bf8241b', 'e96fc2d3', '940dab28', '0a237cf9', '41

In [56]:
#对app_id进行w2v

values = set(app_id)
w2v = []
for i in values:
    a = [i]
    try:
       a.extend(model[i])
       w2v.append(a)
    except:
       print("word {} not in vocabulary".format(i))
out_df = pd.DataFrame(w2v)

#print(model.similar_by_word('50e219e0'))

name = ['app_id']
for i in range(L):
    name.append(name[0] + 'W' + str(i))
out_df.columns = name
out_df.to_csv( 'app_id_em.csv', index=False)

print(out_df.head(20))

c:\users\lx\appdata\local\programs\python\python37\lib\site-packages\ipykernel_launcher.py:8: DeprecationWarning: Call to deprecated `__getitem__` (Method will be removed in 4.0.0, use self.wv.__getitem__() instead).
  


word d2bb6502 not in vocabulary
word 57732071 not in vocabulary
word c776ba2a not in vocabulary
word 7246108e not in vocabulary
word 9a6fd16e not in vocabulary
word 7358e05e not in vocabulary
word 965b8076 not in vocabulary
word 93def835 not in vocabulary
word 84f38fd4 not in vocabulary
word c0a736f4 not in vocabulary
word fc18bf60 not in vocabulary
word 431a0d44 not in vocabulary
word 1cab4fa2 not in vocabulary
word 3f94d062 not in vocabulary
word 46774ea6 not in vocabulary
word e109e9bd not in vocabulary
word 643e0f88 not in vocabulary
word fce64fd5 not in vocabulary
word 3a0b366d not in vocabulary
word 5adb10d9 not in vocabulary
word 5064623a not in vocabulary
word 3872e70d not in vocabulary
word 75807b96 not in vocabulary
word e8966fa6 not in vocabulary
word b88555e4 not in vocabulary
word 6cb77b01 not in vocabulary
word 2c1fa267 not in vocabulary
word 7f4e4ce0 not in vocabulary
word 82cda4e7 not in vocabulary
word 34a4549e not in vocabulary
word 644cb0b0 not in vocabulary
word 659

      app_id  app_idW0  app_idW1  app_idW2  app_idW3  app_idW4  app_idW5
0   92e72531 -0.031269  0.099304  0.139242 -0.432129  0.029873 -0.150706
1   eac7f9fe -0.056164  0.057667  0.096853 -0.036289 -0.085594 -0.037308
2   31b44087 -0.068384 -0.023421  0.027812 -0.008616  0.035715  0.017410
3   9224b468 -0.040934 -0.058630 -0.009534  0.073229 -0.057378  0.035525
4   422df6d6 -0.226074  0.335615  0.395922 -0.754358 -0.085667 -0.333720
5   99709a59 -0.053077 -0.052461  0.019387 -0.048248  0.004519  0.002701
6   f75da770 -0.107535  0.322089  0.445075 -0.724959 -0.171518 -0.275826
7   3ebe76e6 -0.353327  0.328046  0.358087 -0.779036 -0.318686 -0.350308
8   d644e4e7 -2.139451  1.202026  1.453448  0.025625  0.395655 -0.263594
9   6485e293  0.047173 -0.029089 -0.035343 -0.038040  0.069314 -0.043310
10  32556a5f  0.009194  0.069164  0.068377 -0.070508 -0.035536  0.052332
11  9ac6882b -0.102469  0.301364  0.412576 -0.731178 -0.197253 -0.301269
12  f1f93810 -0.160401  0.215934  0.270080 -0.54404

In [57]:
#以下对site_id进行类似处理
import pickle
temp = pickle.load(open('site_id_history.pkl', 'rb'))
print(type(temp))

<class 'dict'>


In [58]:
L=6
sentence = []
for user,user_site_id_history in temp.items():
    sentence.append(user_site_id_history)
#print(sentence[:6])

[['6ddf0cfe', 'fa95a630', '6ddf0cfe', '15941585', '15941585', '87cb5f55', 'a38dc379', 'a38dc379'], ['43999cb9', '43999cb9', '43999cb9', '15941585'], ['cf3a1767', 'cf3a1767', 'cf3a1767', 'cf3a1767', 'a38dc379'], ['887a4754', '887a4754', '53cdb927', '887a4754', '53cdb927', '887a4754'], ['15941585', 'cf3a1767', 'cf3a1767', 'cf3a1767', '61742004', 'cf3a1767', 'cf3a1767'], ['e7eebe29', 'c74e86fb', 'c74e86fb']]


In [59]:
model = Word2Vec(sentence, size=L, window=2, min_count=1, workers=multiprocessing.cpu_count())

In [60]:
model['6ddf0cfe']

c:\users\lx\appdata\local\programs\python\python37\lib\site-packages\ipykernel_launcher.py:1: DeprecationWarning: Call to deprecated `__getitem__` (Method will be removed in 4.0.0, use self.wv.__getitem__() instead).
  """Entry point for launching an IPython kernel.


array([ 0.1667011 ,  0.569009  , -0.8672544 , -0.2026461 , -0.40766203,
        0.43782192], dtype=float32)

In [61]:
site_id=pickle.load(open('site_id.pkl', 'rb'))

In [81]:
print(len(site_id))

1176


In [67]:
#对site_id进行w2v

values = set(site_id)
w2v = []
for i in values:
    a = [i]
    try:
       a.extend(model[i])
       w2v.append(a)
    except:
       print("word {} not in vocabulary".format(i))
out_df = pd.DataFrame(w2v)

#print(model.similar_by_word('50e219e0'))

name = ['site_id']
for i in range(L):
    name.append(name[0] + 'W' + str(i))
out_df.columns = name
out_df.to_csv( 'site_id_em.csv', index=False)

print(out_df.head(20))

c:\users\lx\appdata\local\programs\python\python37\lib\site-packages\ipykernel_launcher.py:8: DeprecationWarning: Call to deprecated `__getitem__` (Method will be removed in 4.0.0, use self.wv.__getitem__() instead).
  


word c304a16c not in vocabulary
word 8fd988d0 not in vocabulary
word 26edd5a1 not in vocabulary
word a187a464 not in vocabulary
word 10a74e5b not in vocabulary
word 48c42b43 not in vocabulary
word 578f2a01 not in vocabulary
word 9c3674a4 not in vocabulary
word c9ec94f6 not in vocabulary
word c3c7062c not in vocabulary
word a3ffa5c9 not in vocabulary
word 6bafb3c4 not in vocabulary
word f2ad8eb5 not in vocabulary
word 63e90429 not in vocabulary
word 3525557b not in vocabulary
word ca5d2559 not in vocabulary
word 6dd700ba not in vocabulary
word 45ddf8ef not in vocabulary
word c04bee75 not in vocabulary
word 7152a402 not in vocabulary
word 47cb5f41 not in vocabulary
word 531483c1 not in vocabulary
word 664d68dc not in vocabulary
word 1ed0fa5f not in vocabulary
word 97b6e615 not in vocabulary
word f48b083d not in vocabulary
word da79c793 not in vocabulary
word baad47dc not in vocabulary
word 33061721 not in vocabulary
word 4bc53306 not in vocabulary
word 43872ea5 not in vocabulary
word 5f6

In [69]:
#以下对site_domain进行类似处理
import pickle
temp = pickle.load(open('site_domain_history.pkl', 'rb'))
print(type(temp))

<class 'dict'>


In [70]:
L=6
sentence = []
for user,user_site_domain_history in temp.items():
    sentence.append(user_site_domain_history)
#print(sentence[:6])

[['7f712270', 'e279a4d6', '7f712270', '0150cc3e', '0150cc3e', '1230bd67', 'a00aeee9', 'a00aeee9'], ['f2c0a99e', 'c4e18dd6', 'f2c0a99e', 'f2c0a99e'], ['8527bd1d', '8527bd1d', '8527bd1d', '1c4b66dd'], ['a00aeee9', '82a51fc9', '82a51fc9', '82a51fc9'], ['c4e18dd6', 'dd7026ee', 'c4e18dd6', 'c4e18dd6'], ['c4e18dd6', 'c4e18dd6', 'c4e18dd6', 'b53723be']]


In [71]:
model = Word2Vec(sentence, size=L, window=2, min_count=1, workers=multiprocessing.cpu_count())

In [72]:
model['7f712270']

c:\users\lx\appdata\local\programs\python\python37\lib\site-packages\ipykernel_launcher.py:1: DeprecationWarning: Call to deprecated `__getitem__` (Method will be removed in 4.0.0, use self.wv.__getitem__() instead).
  """Entry point for launching an IPython kernel.


array([ 0.37069923, -0.02169421,  0.5069283 ,  0.64000756, -0.5652939 ,
        0.19057456], dtype=float32)

In [84]:
site_domain=pickle.load(open('site_domain.pkl', 'rb'))

In [88]:
print(len(site_domain))

1060


In [89]:
#对site_domain进行w2v

values = set(site_domain)
w2v = []
for i in values:
    a = [i]
    try:
       a.extend(model[i])
       w2v.append(a)
    except:
       print("word {} not in vocabulary".format(i))
out_df = pd.DataFrame(w2v)

#print(model.similar_by_word('50e219e0'))

name = ['site_domain']
for i in range(L):
    name.append(name[0] + 'W' + str(i))
out_df.columns = name
out_df.to_csv( 'site_domain_em.csv', index=False)

print(out_df.head(20))

c:\users\lx\appdata\local\programs\python\python37\lib\site-packages\ipykernel_launcher.py:8: DeprecationWarning: Call to deprecated `__getitem__` (Method will be removed in 4.0.0, use self.wv.__getitem__() instead).
  


word 7b8eb0ef not in vocabulary
word f2303555 not in vocabulary
word 480c232d not in vocabulary
word cb2b51dd not in vocabulary
word 23122eaf not in vocabulary
word 9e810ca7 not in vocabulary
word 149ef1a6 not in vocabulary
word 99e23224 not in vocabulary
word 6648d6af not in vocabulary
word 989eeac1 not in vocabulary
word 2a48d61f not in vocabulary
word 31d001be not in vocabulary
word 754f4003 not in vocabulary
word 47b6debc not in vocabulary
word 5bd21703 not in vocabulary
word ad3c3002 not in vocabulary
word bcfde35c not in vocabulary
word d140749b not in vocabulary
word e3491659 not in vocabulary
word a7aa6b70 not in vocabulary
word 88b3d548 not in vocabulary
word 220eb021 not in vocabulary
word c8ae3354 not in vocabulary
word 2b02c0e0 not in vocabulary
word 61fa56ea not in vocabulary
word 6575e16b not in vocabulary
word 12ac9a61 not in vocabulary
word bd3f554a not in vocabulary
word 5b9c601f not in vocabulary
word 274ddcab not in vocabulary
word 51169db6 not in vocabulary
word c7f